<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pegawai;

class PegawaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pegawai = [
            [
                'id' => 1,
                'unit_kerja_id' => 1,
                'jenis_pegawai_id' => 3,
                'status_pegawai_id' => 1,
                'nip' => '199001012020011999',
                'ktp' => '3171010101900999',
                'npwp' => '091234567812999',
                'nama' => 'SDM Yayasan',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Kom',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-01-01',
                'tanggal_bergabung' => '2020-01-01',
                'tanggal_habis_kontrak' => null,
                'tanggal_pensiun' => '2055-01-01',
                'jenis_kelamin' => 'L',
                'alamat_ktp' => 'Jl. Letjen Suprapto, Cempaka Putih, Jakarta Pusat',
                'alamat_domisili' => 'Jl. Letjen Suprapto, Cempaka Putih, Jakarta Pusat',
                'no_telpon' => '081234567999',
                'email_yarsi' => 'sdmyayasan@yarsi.ac.id',
                'status' => 'active',
            ],
            [
                'id' => 2,
                'unit_kerja_id' => 5,
                'jenis_pegawai_id' => 3,
                'status_pegawai_id' => 1,
                'nip' => '199001012020011888',
                'ktp' => '3171010101900888',
                'npwp' => '091234567812888',
                'nama' => 'SDM Universitas',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Kom',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-01-01',
                'tanggal_bergabung' => '2020-01-01',
                'tanggal_habis_kontrak' => null,
                'tanggal_pensiun' => '2055-01-01',
                'jenis_kelamin' => 'L',
                'alamat_ktp' => 'Jl. Letjen Suprapto, Cempaka Putih, Jakarta Pusat',
                'alamat_domisili' => 'Jl. Letjen Suprapto, Cempaka Putih, Jakarta Pusat',
                'no_telpon' => '081234567888',
                'email_yarsi' => 'sdmuniversitas@yarsi.ac.id',
                'status' => 'active',
            ],
            [
                'id' => 3,
                'unit_kerja_id' => 10,
                'jenis_pegawai_id' => 3,
                'status_pegawai_id' => 1,
                'nip' => '199001012020011333',
                'ktp' => '3171010101900333',
                'npwp' => '091234567812333',
                'nama' => 'Taufiq Hakim',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Kom',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-01-01',
                'tanggal_bergabung' => '2020-01-01',
                'tanggal_habis_kontrak' => null,
                'tanggal_pensiun' => '2055-01-01',
                'jenis_kelamin' => 'L',
                'alamat_ktp' => 'Jl. Letjen Suprapto, Cempaka Putih, Jakarta Pusat',
                'alamat_domisili' => 'Jl. Letjen Suprapto, Cempaka Putih, Jakarta Pusat',
                'no_telpon' => '081234567333',
                'email_yarsi' => 'taufiq@yarsi.ac.id',
                'status' => 'active',
            ],
            [
                'id' => 4,
                'unit_kerja_id' => 10,
                'jenis_pegawai_id' => 3,
                'status_pegawai_id' => 1,
                'nip' => '199001012020011777',
                'ktp' => '3171010101900777',
                'npwp' => '091234567812777',
                'nama' => 'Ramadhan Prinada',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Kom',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-01-01',
                'tanggal_bergabung' => '2020-01-01',
                'tanggal_habis_kontrak' => null,
                'tanggal_pensiun' => '2055-01-01',
                'jenis_kelamin' => 'L',
                'alamat_ktp' => 'Jl. Letjen Suprapto, Cempaka Putih, Jakarta Pusat',
                'alamat_domisili' => 'Jl. Letjen Suprapto, Cempaka Putih, Jakarta Pusat',
                'no_telpon' => '081234567777',
                'email_yarsi' => 'ramadhanprinada@yarsi.ac.id',
                'status' => 'active',
            ],
            [
                'id' => 5,
                'unit_kerja_id' => 11,
                'jenis_pegawai_id' => 3,
                'status_pegawai_id' => 1,
                'nip' => '199001012020011222',
                'ktp' => '3171010101900222',
                'npwp' => '091234567812222',
                'nama' => 'Wily Ahmad',
                'gelar_depan' => null,
                'gelar_belakang' => 'M.Kom',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1990-01-01',
                'tanggal_bergabung' => '2020-01-01',
                'tanggal_habis_kontrak' => null,
                'tanggal_pensiun' => '2055-01-01',
                'jenis_kelamin' => 'L',
                'alamat_ktp' => 'Jl. Letjen Suprapto, Cempaka Putih, Jakarta Pusat',
                'alamat_domisili' => 'Jl. Letjen Suprapto, Cempaka Putih, Jakarta Pusat',
                'no_telpon' => '081234567222',
                'email_yarsi' => 'wilyahmad@yarsi.ac.id',
                'status' => 'active',
            ],
            [
                'id' => 6,
                'unit_kerja_id' => 2,
                'jenis_pegawai_id' => 3,
                'status_pegawai_id' => 2,
                'nip' => '200101012024011555',
                'ktp' => '3171010101010555',
                'npwp' => '092345678912555',
                'nama' => 'Umam Syafiul',
                'gelar_depan' => null,
                'gelar_belakang' => 'S.Kom',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2001-01-01',
                'tanggal_bergabung' => '2024-01-01',
                'tanggal_habis_kontrak' => '2027-01-01',
                'tanggal_pensiun' => null,
                'jenis_kelamin' => 'L',
                'alamat_ktp' => 'Jl. Salemba Raya, Jakarta Pusat',
                'alamat_domisili' => 'Jl. Salemba Raya, Jakarta Pusat',
                'no_telpon' => '081234567555',
                'email_yarsi' => 'umamsyafiul@yarsi.ac.id',
                'status' => 'active',
            ],
            [
                'id' => 7,
                'unit_kerja_id' => 10,
                'jenis_pegawai_id' => 3,
                'status_pegawai_id' => 2,
                'nip' => '200101012024011666',
                'ktp' => '3171010101010666',
                'npwp' => '092345678912666',
                'nama' => 'Rafly Eryan',
                'gelar_depan' => null,
                'gelar_belakang' => 'S.Kom',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2001-01-01',
                'tanggal_bergabung' => '2012-01-01',
                'tanggal_habis_kontrak' => '2027-01-01',
                'tanggal_pensiun' => null,
                'jenis_kelamin' => 'L',
                'alamat_ktp' => 'Jl. Salemba Raya, Jakarta Pusat',
                'alamat_domisili' => 'Jl. Salemba Raya, Jakarta Pusat',
                'no_telpon' => '081234567666',
                'email_yarsi' => 'raflyeryan@yarsi.ac.id',
                'status' => 'active',
            ],
            [
                'id' => 8,
                'unit_kerja_id' => 11,
                'jenis_pegawai_id' => 3,
                'status_pegawai_id' => 2,
                'nip' => '200101012024011111',
                'ktp' => '3171010101010111',
                'npwp' => '092345678912111',
                'nama' => 'Hilal Rizqi',
                'gelar_depan' => null,
                'gelar_belakang' => 'S.Kom',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2001-01-01',
                'tanggal_bergabung' => '2024-01-01',
                'tanggal_habis_kontrak' => '2027-01-01',
                'tanggal_pensiun' => null,
                'jenis_kelamin' => 'L',
                'alamat_ktp' => 'Jl. Salemba Raya, Jakarta Pusat',
                'alamat_domisili' => 'Jl. Salemba Raya, Jakarta Pusat',
                'no_telpon' => '081234567891',
                'email_yarsi' => 'hilalrizqi@yarsi.ac.id',
                'status' => 'active',
            ],
            [
                'id' => 9,
                'unit_kerja_id' => 2,
                'jenis_pegawai_id' => 3,
                'status_pegawai_id' => 2,
                'nip' => '200101012024011444',
                'ktp' => '3171010101010444',
                'npwp' => '092345678912444',
                'nama' => 'Isa Agiya',
                'gelar_depan' => null,
                'gelar_belakang' => 'S.Kom',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2001-01-01',
                'tanggal_bergabung' => '2024-01-01',
                'tanggal_habis_kontrak' => '2027-01-01',
                'tanggal_pensiun' => null,
                'jenis_kelamin' => 'L',
                'alamat_ktp' => 'Jl. Salemba Raya, Jakarta Pusat',
                'alamat_domisili' => 'Jl. Salemba Raya, Jakarta Pusat',
                'no_telpon' => '081234567444',
                'email_yarsi' => 'isagiyaa@yarsi.ac.id',
                'status' => 'active',
            ],
            
        ];

        Pegawai::unguarded(function () use ($pegawai) {
            foreach ($pegawai as $data) {
                Pegawai::updateOrCreate(
                    ['id' => $data['id']],
                    $data
                );
            }
        });
    }
}
